name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build backend
    - name: Build backend image
      run: docker build -t thivh/codingtestspx-backend:latest ./backend

    - name: Push backend image
      run: docker push thivh/codingtestspx-backend:latest

    # Build frontend
    - name: Build frontend image
      run: docker build -t thivh/codingtestspx-frontend:latest ./frontend

    - name: Push frontend image
      run: docker push thivh/codingtestspx-frontend:latest
